name: Deploy to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      - self-hosted
      - Linux
      - X64
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config --global user.name "piyjeem277"
          git config --global user.email "piyumanthajm@gmail.com"

      - name: Preparing local repository
        run: /var/www/smsdir/deploy_prepare_repo.sh

      - name: Preparing composer
        run: /var/www/smsdir/deploy_prepare_composer.sh

      - name: Building for production
        run: /var/www/smsdir/deploy_npm_build.sh

      - name: Cleaning up & reloading service
        run: /var/www/smsdir/deploy_clean_reload.sh
